#!/usr/bin/env bash
set -euo pipefail

# This script normalizes sibling dependencies according to their Patchwork role:
# - Patchwork mods keep a local path dependency because composition and codegen
#   need the mod directory itself;
# - plain library crates use the remote Git repository and are overridden
#   locally through config.toml during development.
# Put this file in mods/.cargo/.
# It works regardless of whether it is launched from mods/ or mods/.cargo/.

# Example
#
# [dependencies]
# lifecycle-mod = { git = "https://github.com/paolobettelini/modularis.git" }
# helper-lib = { path = "../helper-lib", features = ["abc"] }
#
# turns into
#
# [dependencies]
# lifecycle-mod = { path = "../lifecycle-mod" }
# helper-lib = { git = "https://github.com/paolobettelini/modularis.git", features = ["abc"] }
#
# config.toml overrides only helper-lib with its local checkout.

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
mods_dir="$(dirname -- "$script_dir")"
config_path="$script_dir/config.toml"
repo_url="https://github.com/paolobettelini/modularis.git"

dry_run=0
for arg in "$@"; do
    case "$arg" in
        --dry-run) dry_run=1 ;;
        *)
            echo "usage: $(basename -- "$0") [--dry-run]" >&2
            exit 2
            ;;
    esac
done

for cmd in perl awk mktemp cmp diff; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        echo "error: $cmd is required" >&2
        exit 1
    fi
done

shopt -s nullglob
manifests=("$mods_dir"/*/Cargo.toml)
shopt -u nullglob

if ((${#manifests[@]} == 0)); then
    echo "error: no Cargo.toml found directly under $mods_dir" >&2
    exit 1
fi

config_tmp="$(mktemp)"
crate_map_tmp="$(mktemp)"
cleanup() {
    rm -f -- "$config_tmp" "$crate_map_tmp"
}
trap cleanup EXIT

# Build the package/folder/kind map and config.toml first. Package names come
# from [package].name; paths are relative to mods/ because config.toml lives in
# mods/.cargo/. A crate is a Patchwork mod exactly when it declares
# [package.metadata.mod].
printf '%s\n' '# Generated by .cargo/sync-modularis-deps.sh. Do not edit by hand.' > "$config_tmp"
printf '[patch."%s"]\n' "$repo_url" >> "$config_tmp"

library_count=0
for manifest in "${manifests[@]}"; do
    crate_dir="$(dirname -- "$manifest")"
    folder="$(basename -- "$crate_dir")"

    package_name="$(awk '
        BEGIN { in_package = 0 }
        /^[[:space:]]*\[package\][[:space:]]*(#.*)?$/ {
            in_package = 1
            next
        }
        /^[[:space:]]*\[/ {
            if (in_package) exit
        }
        in_package && /^[[:space:]]*name[[:space:]]*=/ {
            line = $0
            sub(/^[[:space:]]*name[[:space:]]*=[[:space:]]*/, "", line)
            sub(/[[:space:]]*#.*/, "", line)
            gsub(/^[[:space:]]+|[[:space:]]+$/, "", line)

            quote = substr(line, 1, 1)
            if (quote == "\"" || quote == sprintf("%c", 39)) {
                line = substr(line, 2)
                pos = index(line, quote)
                if (pos > 0) line = substr(line, 1, pos - 1)
            }

            print line
            exit
        }
    ' "$manifest")"

    if [[ -z "$package_name" ]]; then
        echo "warning: cannot find [package].name in $manifest; skipping it" >&2
        continue
    fi

    # Development copies of codegen outputs may appear under mods/ after a
    # compose. They are ephemeral generated crates, not remote libraries and
    # not Patchwork registry projects, so they must never enter the Git patch
    # map or affect dependency classification.
    if [[ "$package_name" == generated-* ]]; then
        continue
    fi

    if [[ "$folder" == *'"'* ]]; then
        echo "error: unsupported double quote in crate folder name: $folder" >&2
        exit 1
    fi

    is_mod="$(awk '
        /^[[:space:]]*\[package\.metadata\.mod\][[:space:]]*(#.*)?$/ {
            print 1
            exit
        }
    ' "$manifest")"
    if [[ "$is_mod" != "1" ]]; then
        is_mod=0
        printf '%s = { path = "%s" }\n' "$package_name" "$folder" >> "$config_tmp"
        ((library_count += 1))
    fi

    printf '%s\t%s\t%s\n' "$package_name" "$folder" "$is_mod" >> "$crate_map_tmp"
done

# Normalize sibling dependencies in both directions. Inline dependency tables
# may use `package = "..."`; dependency subtables are resolved by their key.
# Dev/build/target/workspace dependency sections are supported as well.
export MODS_DIR="$mods_dir"
export REPO_URL="$repo_url"
export CRATE_MAP_PATH="$crate_map_tmp"

read -r -d '' perl_program <<'PERL' || true
BEGIN {
    $in_dep_table = 0;
    $in_dep_subtable = 0;
    $dep_subtable_package = undef;

    open my $map, "<", $ENV{CRATE_MAP_PATH}
        or die "cannot open crate map $ENV{CRATE_MAP_PATH}: $!";
    while (my $line = <$map>) {
        chomp $line;
        my ($package, $folder, $is_mod) = split /\t/, $line, 3;
        $folder_by_package{$package} = $folder;
        $is_mod_by_package{$package} = $is_mod;
        $is_mod_by_folder{$folder} = $is_mod;
    }
    close $map;
}

if (/^\s*\[([^\]]+)\]\s*(?:#.*)?$/) {
    my $section = $1;

    $in_dep_table = (
        $section =~ /^(?:dependencies|dev-dependencies|build-dependencies|workspace\.dependencies)$/
        || $section =~ /^target\..*\.(?:dependencies|dev-dependencies|build-dependencies)$/
    );

    $in_dep_subtable = 0;
    $dep_subtable_package = undef;
    if (
        $section =~ /(?:^|\.)(?:dependencies|dev-dependencies|build-dependencies)\.([A-Za-z0-9_.-]+)$/
    ) {
        $in_dep_subtable = 1;
        $dep_subtable_package = $1;
    }
}

if ($in_dep_table) {
    # Existing sibling paths are valid only for Patchwork mods. Plain local
    # libraries remain distributable Git dependencies.
    if (/\bpath\s*=\s*(["\x27])\.\.\/([^\/"\x27]+)\/?\1/) {
        my $folder = $2;
        if (
            -f "$ENV{MODS_DIR}/$folder/Cargo.toml"
            && exists $is_mod_by_folder{$folder}
            && !$is_mod_by_folder{$folder}
        ) {
            s/\bpath\s*=\s*(["\x27])\.\.\/\Q$folder\E\/?\1/git = "$ENV{REPO_URL}"/;
        }
    }

    # A Git dependency that names a local Patchwork mod must point at the
    # sibling directory. Prefer an explicit package alias when present.
    if (/^\s*([A-Za-z0-9_.-]+)\s*=\s*\{/) {
        my $package = $1;
        if (/\bpackage\s*=\s*(["\x27])([^"\x27]+)\1/) {
            $package = $2;
        }
        if (
            exists $folder_by_package{$package}
            && $is_mod_by_package{$package}
        ) {
            my $folder = $folder_by_package{$package};
            s/\bgit\s*=\s*(["\x27])\Q$ENV{REPO_URL}\E\1/path = "..\/$folder"/;
        }
    }
}
elsif ($in_dep_subtable) {
    if (/^\s*path\s*=\s*(["\x27])\.\.\/([^\/"\x27]+)\/?\1/) {
        my $folder = $2;
        if (
            -f "$ENV{MODS_DIR}/$folder/Cargo.toml"
            && exists $is_mod_by_folder{$folder}
            && !$is_mod_by_folder{$folder}
        ) {
            s/^(\s*)path(\s*=\s*)(["\x27])\.\.\/\Q$folder\E\/?\3/$1git$2"$ENV{REPO_URL}"/;
        }
    }
    elsif (
        /^\s*git\s*=\s*(["\x27])\Q$ENV{REPO_URL}\E\1/
        && defined $dep_subtable_package
        && exists $folder_by_package{$dep_subtable_package}
        && $is_mod_by_package{$dep_subtable_package}
    ) {
        my $folder = $folder_by_package{$dep_subtable_package};
        s/^(\s*)git(\s*=\s*)(["\x27])\Q$ENV{REPO_URL}\E\3/$1path$2"..\/$folder"/;
    }
}
PERL

changed_files=0
for manifest in "${manifests[@]}"; do
    candidate="$(mktemp)"

    if ! perl -pe "$perl_program" "$manifest" > "$candidate"; then
        echo "error: failed to process $manifest" >&2
        rm -f -- "$candidate"
        exit 1
    fi

    if ! cmp -s -- "$manifest" "$candidate"; then
        ((changed_files += 1))

        if ((dry_run)); then
            echo
            diff -u -- "$manifest" "$candidate" || true
        else
            cat -- "$candidate" > "$manifest"
        fi
    fi

    rm -f -- "$candidate"
done

if ((dry_run)); then
    if [[ -f "$config_path" ]]; then
        if ! cmp -s -- "$config_path" "$config_tmp"; then
            echo
            diff -u -- "$config_path" "$config_tmp" || true
        fi
    else
        echo
        echo "--- $config_path (new)"
        cat -- "$config_tmp"
    fi
else
    cat -- "$config_tmp" > "$config_path"
fi

echo
if ((dry_run)); then
    echo "dry-run: $changed_files Cargo.toml file(s) would change"
    echo "dry-run: config.toml would contain $library_count local library patch(es)"
else
    echo "rewritten: $changed_files Cargo.toml file(s)"
    echo "generated: $config_path ($library_count local library patch(es))"
fi
